apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "user"
      containers:
      - name: user-microservice
        image: user-microservice:v1
        env:
        - name: MONGODB_URL
          value: mongodb://192.168.49.2:32323/user_collection?authSource=admin&retryWrites=true&w=majority
        - name: JWT_SECRET_KEY
          value: c91ea84ece6952df6f0819747ac07d79a9845cff4a8f745c6f23cb0351af6e1b
        - name: JWT_REFRESH_SECRET_KEY
          value: 992ac25d558881bae6eeb90518886eebab61e7f36354543901fa11c9b57da44e
      - name: user-mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017

